FROM kir.alibaba-inc.com/kis-docker-hub/amd:alinux3-rocm_6.4.1-py_3.10_2025_04_27_14_59_43

## Basic arguments and environment parameters
ARG GFX_ARCH="gfx942"
ARG GPU_DEVICE_TARGETS="gfx942"
ENV _GLIBCXX_USE_CXX11_ABI=1
ARG PYTHON_VERSION=3.10

ENV PATH="/opt/rocm/bin:/opt/cmake/cmake-3.26.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV ROCM_HOME="/opt/rocm-6.4.1"

ARG TORCH_BRANCH="v2.7.1"
ARG TORCH_COMMIT="e2d141d"
ARG PYTORCH_ROCM_ARCH=gfx942
ENV PYTORCH_ROCM_ARCH=${PYTORCH_ROCM_ARCH}

RUN rm -f /etc/yum.repos.d/amdgpu.repo && \
    dnf install -y python3 python3-devel wget git cmake gcc gcc-c++ ninja-build libsndfile && \
    dnf clean all

# (Optional) Download AOTriton to accelerate the build process
# Please check AOTriton version in cmake/External/aotriton.cmake
# cd /opt
# wget https://github.com/ROCm/aotriton/releases/download/0.9.2b/aotriton-0.9.2b-manylinux_2_28_x86_64-rocm6.4-shared.tar.gz
# tar zxf aotriton-0.9.2b-manylinux_2_28_x86_64-rocm6.4-shared.tar.gz
# export AOTRITON_INSTALLED_PREFIX=/opt/aotriton

# Build PyTorch from source
#RUN dnf install -y intel-oneapi-common-vars intel-oneapi-mkl
#RUN dnf install -y intel-mkl
RUN tee /etc/yum.repos.d/oneAPI.repo <<'EOF'
[oneAPI]
name=Intel® oneAPI repository
baseurl=https://yum.repos.intel.com/oneapi
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
EOF

RUN dnf install -y intel-oneapi-mkl-devel-2024.2.0

ENV MKLROOT=/opt/intel/oneapi/mkl/2024.2
ENV LD_LIBRARY_PATH=$MKLROOT/lib/intel64:$LD_LIBRARY_PATH
ENV CPATH=$MKLROOT/include:$CPATH
ENV LIBRARY_PATH=$MKLROOT/lib/intel64:$LIBRARY_PATH

RUN cd /opt && git clone -b $TORCH_BRANCH --single-branch https://github.com/ROCm/pytorch.git
WORKDIR /opt/pytorch

RUN git checkout $TORCH_COMMIT && git submodule update --init --recursive
RUN python3 -m pip install cmake==3.26.4
RUN python3 -m pip install -r requirements.txt
RUN python3 tools/amd_build/build_amd.py
RUN python3 setup.py bdist_wheel --dist-dir=dist

# Install PyTorch
RUN python3 -m pip install ./dist/torch-2.7.1a0+gite2d141d-cp310-cp310-linux_x86_64.whl
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/python${PYTHON_VERSION}/site-packages/torch/lib:$LD_LIBRARY_PATH

# (Optional) Delete AOTriton
# unset AOTRITON_INSTALLED_PREFIX
# rm -rf /opt/aotriton
# rm -rf /opt/aotriton-0.9.2b-manylinux_2_28_x86_64-rocm6.4-shared.tar.gz

WORKDIR /opt
